- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
    - name: install mysql server
      package:
        name: mysql-server
        state: present

    - name: start n enable mysql server
      service:
        name: "{{ 'mysqld' if ansible_os_family == 'RedHat' else 'mysql' }}"
        state: started
        enabled: yes

    # - name: setup root password
    #   command: mysql_secure_installation --set-root-pass '{{ mysql_root_password }}'

    - name: get mysql temporary root password
      shell: grep 'temporary password' /var/log/mysqld.log | tail -1 | awk '{print $NF}'
      register: mysql_temp_password
      changed_when: false

    - name: check if mysql root password is already set (custom password works)
      command: mysqladmin -u root -p'{{ mysql_root_password }}' status
      register: mysql_root_pass_check
      ignore_errors: yes
      changed_when: false
      no_log: true

    - name: set mysql root password using temp password
      command: >
        mysql -u root -p'{{ mysql_temp_password.stdout }}'
        --connect-expired-password
        -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
      when: mysql_root_pass_check.rc != 0
      no_log: true
