- name: configure Shipping server
  hosts: shipping
  become: yes
  tasks:
    - name: Install Maven
      package:
        name: "{{ item }}"
        state: present
      loop:
        - maven
        - mysql

    - name: delete shipping.zip in /tmp
      file:
        path: /tmp/shipping.zip
        state: absent

    - name: download shipping zip file
      get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: Add project system user
      user:
        name: project
        system: yes
        home: /app
        shell: /sbin/nologin
        comment: project system usr
        create_home: no # defaults to yes

    - name: create app directory
      file:
        path: /app
        state: directory
        owner: project
        group: project

    - name: Find all contents in app directory
      ansible.builtin.find:
        paths: /app
        file_type: any
      register: app_contents
      tags: delete-app-content

    - name: Delete all found contents
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ app_contents.files }}"
      tags: delete-app-content

    - name: unzip shipping file
      unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes # the zip file is on the remote target host (catalogue). ansible server is local here.

    - name: Install dependencies & build the application
      command: mvn clean package
      args:
        chdir: /app

    - name: Move n Rename shipping-1.0.jar file
      command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: copy shipping.service.j2
      template:
        src: shipping.service.j2
        dest: /etc/systemd/system/shipping.service

    - name: load mysql data
      shell: mysql -h {{ MYSQL_HOST }} -uroot -p{{ mysql_root_password }} < {{ item }}
      args:
        chdir: /app/db
      loop:
        - schema.sql
        - app-user.sql
        - master-data.sql
      no_log: yes

    - name: Enable and start service with daemon reload
      ansible.builtin.systemd_service:
        name: shipping
        state: started
        enabled: yes
        daemon_reload: yes
