- name: roboshop instances management
  hosts: local
  connection: local
  vars:
    instances:
      [
        "mongodb",
        "redis",
        "mysql",
        "rabbitmq",
        "catalogue",
        "user",
        "cart",
        "shipping",
        "payment",
        "frontend",
      ]
    action: create
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        name: "{{ item }}"
        image_id: "{{ image_id }}"
        security_group: "{{ security_group_id }}"
      loop: "{{ instances }}"
      register: ec2_output
      when: action == "create"

    - name: create r53 DNS records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ domain_name }}"
        type: A
        ttl: 300
        value: "{{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_output.results }}"
      when: action == "create"
